environment                      = "prod"
aws_account_id                   = "111111111111"
aws_region                       = "eu-west-1"
tfstate_bucket                   = "example-terraform-state"
tfstate_bucket_region            = "eu-west-1"
